[project]
name = "english-stimuli-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-mg",
]

[tool.uv.sources]
python-mg = { git = "https://github.com/MichaelGoodale/python-mg" }
