# Output
output_dir: /lustre/fswork/projects/rech/ywa/uds37kc/GTH/results/gpt2_hf

# Optimization
learning_rate: 6.0e-4
weight_decay: 0.1
adam_beta2: 0.95
warmup_ratio: 0.1
max_grad_norm: 1.0

# Batching
train_batch_size: 32
gradient_accumulation_steps: 8
dataloader_num_workers: 4
dataloader_prefetch_factor: 2

# Evaluation / checkpointing
eval_steps: 200
save_steps: 5000
logging_steps: 200


